name: FuelTrackr CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test FuelTrackr
    runs-on: macos-15 # Use the latest macOS version
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Xcode latest-stable
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build
      run: |
        xcodebuild clean build -project FuelTrackr.xcodeproj -scheme FuelTrackr -destination 'platform=iOS Simulator,name=iPhone 16'
    
    # - name: Test
    #   run: |
    #     xcodebuild test -project FuelTrackr.xcodeproj -scheme FuelTrackr -destination 'platform=iOS Simulator,name=iPhone 16'
