name: FuelTrackr CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test FuelTrackr
    runs-on: macos-12 # Use the latest macOS version
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Xcode 14.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    
    - name: Build
      run: |
        xcodebuild clean build -workspace FuelTrackr.xcworkspace -scheme FuelTrackr -destination 'platform=iOS Simulator,name=iPhone 14'
    
    # - name: Test
    #   run: |
    #     xcodebuild test -workspace FuelTrackr.xcworkspace -scheme FuelTrackr -destination 'platform=iOS Simulator,name=iPhone 14'
